export const Translator = {
  EN: {
    student_list: "Student List",
    online_journal: "Online Journal",
    authorize: "Authorization",
    enter: "Enter",
    studium_description: "convenient online journal and student database",
    click_student: "Click on a student in the table for detailed information",
    filters: "Filters",
    search: "Search",
    name_student: "Name",
    age: "Age",
    student_group: "Study Group",
    date_start_stude: "Enrollment Date",
    from: "From",
    to: "To",
    this_year_finish: "Graduates this year",
    this_year_start: "Enrolled this year",
    clear_filters: "Clear Filters",
    journal: "Journal",
    select_group: "Select Group",
    select_student: "Select Student",
    select_subject: "Select Subject",
    add_mark: "Add Mark",
    mark_adding: "Adding Mark",
    date: "Date",
    student: "Student",
    subject: "Subject",
    mark: "Mark",
    profile: "Profile",
    information: "Information",
    performance: "Performance",
    main_information: "Main Information",
    exit: "Exit",
    group: "Group",
    date_birthday: "Date of Birth",
    passport_information: "Passport Information",
    passport_not_load: "Data not loaded",
    passport_load: "Data loaded",
    create_new_student: "Create New Student",
    first_name: "First Name",
    middle_name: "Middle Name",
    last_name: "Last Name",
    sex: "Gender",
    create: "Create",
    edit_student: "Edit Student Data",
    edit: "Edit",
    man: "Male",
    woman: "Female",
    name: "Name",
    teacher: "Teacher",
    descripition: "Description",
    auditory: "Auditory",
    group_number: "Group Number",
    group_create: "Create Group",
    subject_create: "Create Subject",
    group_edit: "Edit Group Data",
    subject_edit: "Edit Subject Data",
    diagrams: "Diagrams",
    marks: "Marks",
    credits: "Credits",
    average_mark_calculation: "Average Mark Calculation",
    calculate_average_mark_for: "Calculate average mark for:",
    calculate: "Calculate",
    marks_lower_3: "Marks below 3",
    marks_highter_3: "Marks above 3",
    pass_works: "Passed Works",
    not_pass_works: "Not Passed Works",
    do_diagrams: "Generate Diagrams",
    average_mark_bad: "You are serious! Try harder!",
    average_mark_normal: "You are good! Great job!",
    average_mark_good: "You are excellent! Keep it up!",
    subject_list: "Subject list",
    curator: "Curator",
    group_list: "Group list",
    create_diagrams: "Generate diagrams",
    login: "Login",
    roles: "Roles",
    user_roles: "User Roles",
    register_user: "Register User",
    user_list: "User List",
    admin: "Admin",
    secretar: "Secretary",
    select_role: "Select Role",
    selecting_role_help:
      "To select a role, choose a role from the dropdown list, to select multiple roles, choose the role again",
    password: "Password",
  },
  BE: {
    student_list: "Спіс навучэнцаў",
    online_journal: "Электронны журнал",
    authorize: "Аўтарызацыя",
    enter: "Увайсці",
    studium_description: "зручны электронны журнал і база дадзеных навучэнцаў",
    click_student:
      "Націсніце на навучэнца ў табліцы для падрабязнай інфармацыі",
    filters: "Фільтры",
    search: "Пошук",
    name_student: "Імя",
    age: "Узрост",
    student_group: "Навучальная група",
    date_start_stude: "Дата залічэння",
    from: "Ад",
    to: "Да",
    this_year_finish: "Выпускнікі гэтага года",
    this_year_start: "Залічаныя ў гэтым годзе",
    clear_filters: "Ачысціць фільтры",
    journal: "Журнал",
    select_group: "Выберыце групу",
    select_student: "Выберыце навучэнца",
    select_subject: "Выберыце прадмет",
    add_mark: "Дадаць адзнаку",
    mark_adding: "Даданне адзнакі",
    date: "Дата",
    student: "Навучэнец",
    subject: "Прадмет",
    mark: "Адзнака",
    profile: "Асабісты кабінет",
    information: "Інфармацыя",
    performance: "Паспяховасць",
    main_information: "Асноўная інфармацыя",
    exit: "Выйсці",
    group: "Група",
    date_birthday: "Дата нараджэння",
    passport_information: "Пашпартныя дадзеныя",
    passport_not_load: "Дадзеныя не загружаны",
    passport_load: "Дадзеныя загружаны",
    create_new_student: "Стварэнне новага студэнта",
    first_name: "Імя",
    middle_name: "Імя па бацьку",
    last_name: "Прозвішча",
    sex: "Пол",
    create: "Стварыць",
    edit_student: "Рэдагаванне дадзеных аб студэнце",
    edit: "Змяніць",
    man: "Мужчынскі",
    woman: "Жаночы",
    name: "Назва",
    teacher: "Выкладчык",
    descripition: "Апісанне",
    auditory: "Аўдыторыя",
    group_number: "Нумар групы",
    group_create: "Стварэнне групы",
    subject_create: "Стварэнне прадмета",
    group_edit: "Рэдагаванне дадзеных аб групе",
    subject_edit: "Рэдагаванне дадзеных аб прадмеце",
    diagrams: "Дыяграмы",
    marks: "Адзнакі",
    credits: "Залікі",
    average_mark_calculation: "Разлік сярэдняга бала",
    calculate_average_mark_for: "Разлічыць сярэдні бал для:",
    calculate: "Разлічыць",
    marks_lower_3: "Адзнакі ніжэй 3",
    marks_highter_3: "Адзнакі вышэй за 3",
    pass_works: "Здадзеныя працы",
    not_pass_works: "Не здадзеныя працы",
    do_diagrams: "Сфармаваць дыяграмы",
    average_mark_bad: "Вы - сур'ёзны тып! Старайцеся лепш!",
    average_mark_normal: "Вы - выдатнік! Выдатна!",
    average_mark_good: "Вы - выдатнік! Так трымаць!",
    subject_list: "Спiс прадметаў",
    curator: "Куратар",
    group_list: "Спic груп",
    create_diagrams: "Сфармаваць дыяграмы",
    login: "Логiн",
    roles: "Ролi",
    user_roles: "Ролі карыстальнікаў",
    register_user: "Зарэгістраваць карыстальніка",
    user_list: "Спіс карыстальнікаў",
    admin: "Адміністратар",
    secretar: "Сакратар",
    select_role: "Выберыце ролю",
    selecting_role_help:
      "Для выбару ролі, выберыце ролю з выпадаючага спісу, для выбару некалькіх роляў, выберыце ролю паўторна",
    password: "Пароль",
  },
  RU: {
    student_list: "Список учащихся",
    online_journal: "Электронный журнал",
    authorize: "Авторизация",
    enter: "Войти",
    studium_description: "удобный электронный журнал и база данных учащихся",
    click_student: "Нажмите на учащегося в таблице для подробной информации",
    filters: "Фильтры",
    search: "Поиск",
    name_student: "Имя",
    age: "Возраст",
    student_group: "Учебная группа",
    date_start_stude: "Дата зачисления",
    from: "От",
    to: "До",
    this_year_finish: "Выпуск этого года",
    this_year_start: "Зачисленные в этом году",
    clear_filters: "Очистить фильтры",
    journal: "Журнал",
    select_group: "Выберите группу",
    select_student: "Выберите учащегося",
    select_subject: "Выберите предмет",
    add_mark: "Добавить оценку",
    mark_adding: "Добавление оценки",
    date: "Дата",
    student: "Учащийся",
    subject: "Предмет",
    mark: "Оценка",
    profile: "Личный кабинет",
    information: "Информация",
    performance: "Успеваемость",
    main_information: "Основная информация",
    exit: "Выйти",
    group: "Группа",
    date_birthday: "Дата рождения",
    passport_information: "Паспортные данные",
    passport_not_load: "Данные не загружены",
    passport_load: "Данные загружены",
    create_new_student: "Создание нового студента",
    first_name: "Имя",
    middle_name: "Отчество",
    last_name: "Фамилия",
    sex: "Пол",
    create: "Создать",
    edit_student: "Изменение данных о студенте",
    edit: "Изменить",
    man: "Мужской",
    woman: "Женский",
    name: "Название",
    teacher: "Преподаватель",
    descripition: "Описание",
    auditory: "Аудитория",
    group_number: "Номер группы",
    group_create: "Создание группы",
    subject_create: "Создание предмета",
    group_edit: "Изменение данных о группе",
    subject_edit: "Изменение данных о предмете",
    diagrams: "Диаграммы",
    marks: "Оценки",
    credits: "Зачеты",
    average_mark_calculation: "Расчёт среднего бала",
    calculate_average_mark_for: "Расчитать средний балл для:",
    calculate: "Расчитать",
    marks_lower_3: "Оценки ниже 3",
    marks_highter_3: "Оценки выше трех",
    pass_works: "Сдано работ",
    not_pass_works: "Не сдано работ",
    do_diagrams: "Сформировать диаграммы",
    average_mark_bad: "Вы - серьезный тип! Старайтесь лучше!",
    average_mark_normal: "Вы - хорошист! Отлично!",
    average_mark_good: "Вы - отличник! Так держать!",
    subject_list: "Список предметов",
    curator: "Куратор",
    group_list: "Список групп",
    create_diagrams: "Сформировать диаграммы",
    login: "Логин",
    roles: "Роли",
    user_roles: "Роли пользователей",
    register_user: "Зарегистрировать пользователя",
    user_list: "Список пользователей",
    admin: "Админ",
    secretar: "Секретарь",
    select_role: "Выберите роль",
    selecting_role_help:
      "Для выбора роли, выберите роль из выпадющего списка, для выбора нескольких ролей, выберите роль повторно",
    password: "Пароль",
  },
};
