export const Translator = {
  EN: {
    student_list: "Student List",
    online_journal: "Online Journal",
    authorize: "Authorization",
    enter: "Enter",
    studium_description: "convenient online journal and student database",
    click_student: "Click on a student in the table for detailed information",
    filters: "Filters",
    search: "Search",
    name_student: "Name",
    age: "Age",
    student_group: "Study Group",
    date_start_stude: "Enrollment Date",
    from: "From",
    to: "To",
    this_year_finish: "Graduates this year",
    this_year_start: "Enrolled this year",
    clear_filters: "Clear Filters",
    journal: "Journal",
    select_group: "Select Group",
    select_student: "Select Student",
    select_subject: "Select Subject",
    add_mark: "Add Mark",
    mark_adding: "Adding Mark",
    date: "Date",
    student: "Student",
    subject: "Subject",
    mark: "Mark",
    profile: "Profile",
    information: "Information",
    performance: "Performance",
    main_information: "Main Information",
    exit: "Exit",
    group: "Group",
    date_birthday: "Date of Birth",
    passport_information: "Passport Information",
    passport_not_load: "Data not loaded",
    passport_load: "Data loaded",
    create_new_student: "Create New Student",
    first_name: "First Name",
    middle_name: "Middle Name",
    last_name: "Last Name",
    sex: "Gender",
    create: "Create",
    edit_student: "Edit Student Data",
    edit: "Edit",
    man: "Male",
    woman: "Female",
    name: "Name",
    teacher: "Teacher",
    descripition: "Description",
    auditory: "Auditory",
    group_number: "Group Number",
    group_create: "Create Group",
    subject_create: "Create Subject",
    group_edit: "Edit Group Data",
    subject_edit: "Edit Subject Data",
    diagrams: "Diagrams",
    marks: "Marks",
    credits: "Credits",
    average_mark_calculation: "Average Mark Calculation",
    calculate_average_mark_for: "Calculate average mark for:",
    calculate: "Calculate",
    marks_lower_3: "Marks below 3",
    marks_highter_3: "Marks above 3",
    pass_works: "Passed Works",
    not_pass_works: "Not Passed Works",
    do_diagrams: "Generate Diagrams",
    average_mark_bad: "You are serious! Try harder!",
    average_mark_normal: "You are good! Great job!",
    average_mark_good: "You are excellent! Keep it up!",
    subject_list: "Subject list",
    curator: "Curator",
    group_list: "Group list",
    create_diagrams: "Generate diagrams",
    login: "Login",
    roles: "Roles",
    user_roles: "User Roles",
    register_user: "Register User",
    user_list: "User List",
    admin: "Admin",
    secretar: "Secretary",
    select_role: "Select Role",
    selecting_role_help:
      "To select a role, choose a role from the dropdown list, to select multiple roles, choose the role again",
    password: "Password",
    data_about_start: "Enrollment data",
    date_start: "Enrollment date",
    date_finish: "End date",
    select_sex: "Select sex",
    not_correct_password: "Incorrect password or login",
    error_401: "Error 401",
    user_not_auth: "User is not authorized",
    back_to_main: "Back to main",
    page_not_avaible:
      "The page you are looking for is not found or does not exist.",
    error_404: "Error 404",
    fill_data_full: "Fill in the data completely",
    error_in_data: "Incorrect data, please check the data",
    confirm_delete: "Confirm delete",
    average_grade: "Average grade",
    adding_mark: "Adding a mark",
    grade_type: "Grade type",
    select_type: "Select type",
    practical_work: "Practical work",
    lecture: "Lecture",
    control_work: "Control work",
    subject_name: "Name",
    subject_description: "Description",
    subject_group: "Group",
    group_name: "Name",
    group_description: "Description",
    group_auditory: "Auditory",
  },
  BE: {
    student_list: "Спіс навучэнцаў",
    online_journal: "Электронны журнал",
    authorize: "Аўтарызацыя",
    enter: "Увайсці",
    studium_description: "зручны электронны журнал і база дадзеных навучэнцаў",
    click_student:
      "Націсніце на навучэнца ў табліцы для падрабязнай інфармацыі",
    filters: "Фільтры",
    search: "Пошук",
    name_student: "Імя",
    age: "Узрост",
    student_group: "Навучальная група",
    date_start_stude: "Дата залічэння",
    from: "Ад",
    to: "Да",
    this_year_finish: "Выпускнікі гэтага года",
    this_year_start: "Залічаныя ў гэтым годзе",
    clear_filters: "Ачысціць фільтры",
    journal: "Журнал",
    select_group: "Выберыце групу",
    select_student: "Выберыце навучэнца",
    select_subject: "Выберыце прадмет",
    add_mark: "Дадаць адзнаку",
    mark_adding: "Даданне адзнакі",
    date: "Дата",
    student: "Навучэнец",
    subject: "Прадмет",
    mark: "Адзнака",
    profile: "Асабісты кабінет",
    information: "Інфармацыя",
    performance: "Паспяховасць",
    main_information: "Асноўная інфармацыя",
    exit: "Выйсці",
    group: "Група",
    date_birthday: "Дата нараджэння",
    passport_information: "Пашпартныя дадзеныя",
    passport_not_load: "Дадзеныя не загружаны",
    passport_load: "Дадзеныя загружаны",
    create_new_student: "Стварэнне новага студэнта",
    first_name: "Імя",
    middle_name: "Імя па бацьку",
    last_name: "Прозвішча",
    sex: "Пол",
    create: "Стварыць",
    edit_student: "Рэдагаванне дадзеных аб студэнце",
    edit: "Змяніць",
    man: "Мужчынскі",
    woman: "Жаночы",
    name: "Назва",
    teacher: "Выкладчык",
    descripition: "Апісанне",
    auditory: "Аўдыторыя",
    group_number: "Нумар групы",
    group_create: "Стварэнне групы",
    subject_create: "Стварэнне прадмета",
    group_edit: "Рэдагаванне дадзеных аб групе",
    subject_edit: "Рэдагаванне дадзеных аб прадмеце",
    diagrams: "Дыяграмы",
    marks: "Адзнакі",
    credits: "Залікі",
    average_mark_calculation: "Разлік сярэдняга бала",
    calculate_average_mark_for: "Разлічыць сярэдні бал для:",
    calculate: "Разлічыць",
    marks_lower_3: "Адзнакі ніжэй 3",
    marks_highter_3: "Адзнакі вышэй за 3",
    pass_works: "Здадзеныя працы",
    not_pass_works: "Не здадзеныя працы",
    do_diagrams: "Сфармаваць дыяграмы",
    average_mark_bad: "Вы - сур'ёзны тып! Старайцеся лепш!",
    average_mark_normal: "Вы - выдатнік! Выдатна!",
    average_mark_good: "Вы - выдатнік! Так трымаць!",
    subject_list: "Спiс прадметаў",
    curator: "Куратар",
    group_list: "Спic груп",
    create_diagrams: "Сфармаваць дыяграмы",
    login: "Логiн",
    roles: "Ролi",
    user_roles: "Ролі карыстальнікаў",
    register_user: "Зарэгістраваць карыстальніка",
    user_list: "Спіс карыстальнікаў",
    admin: "Адміністратар",
    secretar: "Сакратар",
    select_role: "Выберыце ролю",
    selecting_role_help:
      "Для выбару ролі, выберыце ролю з выпадаючага спісу, для выбару некалькіх роляў, выберыце ролю паўторна",
    password: "Пароль",
    data_about_start: "Дадзеныя аб зарахаванні",
    date_start: "Дата зарахавання",
    date_finish: "Дата заканчэння",
    select_sex: "Пазначце пол",
    not_correct_password: "Няправільны пароль ці лагін",
    error_401: "Памылка 401",
    user_not_auth: "Карыстальнік не аўтарызаваны",
    back_to_main: "Вярнуцца на галоўную",
    page_not_avaible: "Старонка, якую вы шукаеце, не знойдзена або не існуе.",
    error_404: "Памылка 404",
    fill_data_full: "Запоўніце дадзеныя поўнасцю",
    error_in_data: "Няправільныя дадзеныя, калі ласка, праверце дадзеныя",
    confirm_delete: "Пацвердзіць выдаленне",
    average_grade: "Сярэдні бал",
    adding_mark: "Дадаванне адзнакі",
    grade_type: "Тып адзнакі",
    select_type: "Выберыце тып",
    practical_work: "Практычная работа",
    lecture: "Лекцыя",
    control_work: "Кантрольная работа",
    subject_name: "Назва",
    subject_description: "Апісанне",
    subject_group: "Група",
    group_name: "Назва",
    group_description: "Апісанне",
    group_auditory: "Аўдыторыя",
  },
  RU: {
    student_list: "Список учащихся",
    online_journal: "Электронный журнал",
    authorize: "Авторизация",
    enter: "Войти",
    studium_description: "удобный электронный журнал и база данных учащихся",
    click_student: "Нажмите на учащегося в таблице для подробной информации",
    filters: "Фильтры",
    search: "Поиск",
    name_student: "Имя",
    age: "Возраст",
    student_group: "Учебная группа",
    date_start_stude: "Дата зачисления",
    from: "От",
    to: "До",
    this_year_finish: "Выпуск этого года",
    this_year_start: "Зачисленные в этом году",
    clear_filters: "Очистить фильтры",
    journal: "Журнал",
    select_group: "Выберите группу",
    select_student: "Выберите учащегося",
    select_subject: "Выберите предмет",
    add_mark: "Добавить оценку",
    mark_adding: "Добавление оценки",
    date: "Дата",
    student: "Учащийся",
    subject: "Предмет",
    mark: "Оценка",
    profile: "Личный кабинет",
    information: "Информация",
    performance: "Успеваемость",
    main_information: "Основная информация",
    exit: "Выйти",
    group: "Группа",
    date_birthday: "Дата рождения",
    passport_information: "Паспортные данные",
    passport_not_load: "Данные не загружены",
    passport_load: "Данные загружены",
    create_new_student: "Создание нового студента",
    first_name: "Имя",
    middle_name: "Отчество",
    last_name: "Фамилия",
    sex: "Пол",
    create: "Создать",
    edit_student: "Изменение данных о студенте",
    edit: "Изменить",
    man: "Мужской",
    woman: "Женский",
    name: "Название",
    teacher: "Преподаватель",
    descripition: "Описание",
    auditory: "Аудитория",
    group_number: "Номер группы",
    group_create: "Создание группы",
    subject_create: "Создание предмета",
    group_edit: "Изменение данных о группе",
    subject_edit: "Изменение данных о предмете",
    diagrams: "Диаграммы",
    marks: "Оценки",
    credits: "Зачеты",
    average_mark_calculation: "Расчёт среднего бала",
    calculate_average_mark_for: "Расчитать средний балл для:",
    calculate: "Расчитать",
    marks_lower_3: "Оценки ниже 3",
    marks_highter_3: "Оценки выше трех",
    pass_works: "Сдано работ",
    not_pass_works: "Не сдано работ",
    do_diagrams: "Сформировать диаграммы",
    average_mark_bad: "Вы - серьезный тип! Старайтесь лучше!",
    average_mark_normal: "Вы - хорошист! Отлично!",
    average_mark_good: "Вы - отличник! Так держать!",
    subject_list: "Список предметов",
    curator: "Куратор",
    group_list: "Список групп",
    create_diagrams: "Сформировать диаграммы",
    login: "Логин",
    roles: "Роли",
    user_roles: "Роли пользователей",
    register_user: "Зарегистрировать пользователя",
    user_list: "Список пользователей",
    admin: "Админ",
    secretar: "Секретарь",
    select_role: "Выберите роль",
    selecting_role_help:
      "Для выбора роли, выберите роль из выпадющего списка, для выбора нескольких ролей, выберите роль повторно",
    password: "Пароль",
    data_about_start: "Данные о зачислении",
    date_start: "Дата зачисления",
    date_finish: "Дата окончания",
    select_sex: "Укажите пол",
    not_correct_password: "Не правильный пароль или логин",
    error_401: "Ошибка 401",
    user_not_auth: "Пользователь не авторизован",
    back_to_main: "Вернуться на главную",
    page_not_avaible:
      "Страница, которую вы ищете, не найдена или не существует.",
    error_404: "Ошибка 404",
    fill_data_full: "Заполните данные полностью",
    error_in_data: "Некоректные данные, пожалуйста проверьте данные",
    confirm_delete: "Подтвердить удаление",
    average_grade: "Средний балл",
    adding_mark: "Добавление отметки",
    grade_type: "Тип отметки",
    select_type: "Выберите тип",
    practical_work: "Практическая работа",
    lecture: "Лекция",
    control_work: "Контрольная работа",
    subject_name: "Название",
    subject_description: "Описание",
    subject_group: "Группа",
    group_name: "Название",
    group_description: "Описание",
    group_auditory: "Аудитория",
  },
};
